<?php
ini_set("include_path", "../cake/libs".PATH_SEPARATOR."../../../cake/libs".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once '/home/pancha/Documents/PUC/Proyecto/cake/libs/neat_string.php';

/**
 * Test class for NeatString.
 * Generated by PHPUnit on 2009-10-24 at 13:25:40.
 */
class NeatStringTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var NeatString
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NeatString;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testToRoman().
     */
    public function testToRoman()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testToCompressed().
     */
    public function testToCompressed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRandomPassword().
     */
    public function testRandomPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
